[package]
name = "life"
version = "0.1.0"
edition = "2024"
autobins = true

[[bin]]
name = "unix_client"
path = "src/unix_client.rs"

[[bin]]
name = "tcp_client"
path = "src/tcp_client.rs"

[[bin]]
name = "proxy"
path = "src/proxy/main.rs"

[dependencies]
bytes.workspace = true
tokio.workspace = true
tower.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
