[workspace]
resolver = "3"
members = ["life"]


[workspace.dependencies]
bytes = { version = "1.11.1", features = ["serde"] }
tokio = { version = "1.9.0", features = ["full"] }
tower = { version = "0.5.3", features = ["tokio", "futures-core"] }
tracing = { version = "0.1.44", features = ["async-await"] }
tracing-subscriber = { version = "0.3.22", features = ["tracing"] }
futures = "0.3.32"

[package]
name = "depo"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
tokio.workspace = true
futures.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
h2 = "0.4.13"
http = "1.4.0"
httparse = "1.10.1"
hyper = { version = "1.8.1", features = ["client", "full"] }
pin-project = "1.1.11"
rand = "0.10.0"
rustls = "0.23.37"
rustls-pemfile = "2.2.0"
tokio-rustls = "0.26.4"
